WoodcuttingLogs:
  OAK_LOG:
    displayString: "&7Oak Log"
    harvestChance: "0:50,10:100"
    blockXPAmount: .25
    blockHardness: 1
    renewDuration: 5
  BIRCH_LOG:
    displayString: "&fBirch Log"
    harvestChance: "0:50,20:100"
    blockXPAmount: 1
    blockHardness: 1
    renewDuration: 10
  SPRUCE_LOG:
    displayString: "&5Spruce Log"
    harvestChance: "10:25,40:100"
    blockXPAmount: 1.75
    blockHardness: 2
    renewDuration: 20
  ACACIA_LOG:
    displayString: "&6Acacia Log"
    harvestChance: "20:25,60:100"
    blockXPAmount: 3.25
    blockHardness: 2
    renewDuration: 30
  JUNGLE_LOG:
    displayString: "&eJungle Log"
    harvestChance: "30:25,80:100"
    blockXPAmount: 11.5
    blockHardness: 3
    renewDuration: 45
  DARK_OAK_LOG:
    displayString: "&8Dark Oak Log"
    harvestChance: "40:25,100:87.5"
    blockXPAmount: 16.5
    blockHardness: 3
    renewDuration: 60
WoodcuttingAbilities:
  ChainMiner:
    displayString: "&6Chain Miner"
    itemStackIcon: "REDSTONE_BLOCK"
    descOfAbility: "%1$.2f%% chance of granting haste;%3$d for %2$d second(s) upon mining;a block."
    abilityChance: "25:25,75:50"
    abilityLevels: "1,3"
  XPMiner:
    displayString: "&2XP Miner"
    itemStackIcon: "EXPERIENCE_BOTTLE"
    descOfAbility: "%1$.2f%% chance of dropping 0 - %2$d;xp upon mining a block."
    abilityChance: "50:25,100:75"
    abilityLevels: "1,3"
  LootMiner:
    displayString: "&3Loot Miner"
    itemStackIcon: "CHEST"
    descOfAbility: "%1$.2f%% chance of dropping a;random item upon mining a block."
    abilityChance: "100:0.25,100:0.25"
    abilityLevels: "1,1"